# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-16 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_sch', models.CharField(max_length=30)),
                ('stu_num', models.CharField(max_length=30)),
                ('stu_name', models.CharField(max_length=30)),
                ('into_sch', models.CharField(max_length=30)),
            ],
        ),
    ]
