# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-10 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeldb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.TextField(default='shanghai'),
            preserve_default=False,
        ),
    ]
